/path:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
/path/identity:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
/rpp/conditioned_path:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
/rpp/conditioned_path_identity:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
